In [1]:
%matplotlib inline
from __future__ import division
import matplotlib.pyplot as plt
import numpy as np

In [2]:
from babyreactor.constants import FUEL, REFLECTOR

In [3]:
from babyreactor.matrix import cartesian

In [4]:
print(FUEL)

Material 150.0cm wide with 4 node(s)


In [5]:
REFLECTOR

Material 150.0cm wide with 4 node(s)

In [6]:
np.set_printoptions(precision=2)
print(cartesian(FUEL, REFLECTOR, 0))

[[  1.36e-02  -5.05e-04   0.00e+00   0.00e+00   0.00e+00   0.00e+00]
 [ -5.05e-04   2.72e-02  -5.05e-04   0.00e+00   0.00e+00   0.00e+00]
 [  0.00e+00  -5.05e-04   2.72e-02  -5.05e-04   0.00e+00   0.00e+00]
 [  0.00e+00   0.00e+00   8.95e-01  -1.89e+00   8.95e-01   5.07e-02]]


In [7]:
FUEL.absorption

array([ 0.01,  0.12])